package sample;

import java.sql.Timestamp;

public class Country {

    int countryId;
    String countryName;
    Timestamp createdDate;
    String createdBy;
    Timestamp lastUpdate;
    String lastUpdatedBy;

    /**
     * Constructor for Country. Data provided in database
     * @param countryId Id of country. Database assigned.
     * @param countryName Name of Country.
     * @param createdDate DateTime the country was entered into the database.
     * @param createdBy Username that added the country into the database.
     * @param lastUpdate DateTime the country was last updated in the database.
     * @param lastUpdatedBy Username that last updated the country in the database.
     */
    public Country(int countryId, String countryName, Timestamp createdDate, String createdBy, Timestamp lastUpdate, String lastUpdatedBy) {
        this.countryId = countryId;
        this.countryName = countryName;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastUpdate = lastUpdate;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * Gets the country id.
     * This is an integer generated by the database because it is the Primary Key (PK).
     * @return country id is PK of country table in database.
     */
    public int getCountryId() {
        return countryId;
    }

    /**
     * Sets the country id.
     * This is an integer generated by the database because it is the Primary Key (PK).
     * @param countryId country id is PK of country table in database.
     */
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    /**
     * Gets the country name.
     * @return name of country
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the name of the country.
     * @param countryName name of the country
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * Gets the date the country was added in the database.
     * Database uses UTC for timezone information.
     * @return date in UTC
     */
    public Timestamp getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the date the country was added in the database.
     * Database uses UTC for timezone information.
     * @param createdDate date in UTC that the country was added
     */
    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
}
