package sample;

import tools.DateConverter;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;

public class Country {

    int countryId;
    String countryName;
    Timestamp createdDate;
    String createdBy;
    Timestamp lastUpdate;
    String lastUpdatedBy;

    LocalDateTime createdDateAsLocal;
    LocalDateTime lastUpdateAsLocal;
    ZonedDateTime createdDateAsUtc;
    ZonedDateTime lastUpdateAsUtc;

    /**
     * Constructor for Country. Data provided in database
     * @param countryId Id of country. Database assigned.
     * @param countryName Name of Country.
     * @param createdDate DateTime the country was entered into the database.
     * @param createdBy Username that added the country into the database.
     * @param lastUpdate DateTime the country was last updated in the database.
     * @param lastUpdatedBy Username that last updated the country in the database.
     */
    public Country(int countryId, String countryName, Timestamp createdDate, String createdBy, Timestamp lastUpdate, String lastUpdatedBy) {
        this.countryId = countryId;
        this.countryName = countryName;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastUpdate = lastUpdate;
        this.lastUpdatedBy = lastUpdatedBy;

        this.createdDateAsUtc = DateConverter.convertTimestampToUtc(createdDate);
        this.lastUpdateAsUtc = DateConverter.convertTimestampToUtc(lastUpdate);
        this.createdDateAsLocal = DateConverter.convertZonedToLocal(createdDateAsUtc);
        this.lastUpdateAsLocal = DateConverter.convertZonedToLocal(lastUpdateAsUtc);
    }

    /**
     * Gets the country id.
     * This is an integer generated by the database because it is the Primary Key (PK).
     * @return country id is PK of country table in database.
     */
    public int getCountryId() {
        return countryId;
    }

    /**
     * Sets the country id.
     * This is an integer generated by the database because it is the Primary Key (PK).
     * @param countryId country id is PK of country table in database.
     */
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    /**
     * Gets the country name.
     * @return name of country
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the name of the country.
     * @param countryName name of the country
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * Gets the date the country was added in the database.
     * Database uses UTC for timezone information.
     * @return date in UTC
     */
    public Timestamp getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the date the country was added in the database.
     * Database uses UTC for timezone information.
     * @param createdDate date in UTC that the country was added
     */
    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
        this.createdDateAsUtc = DateConverter.convertTimestampToUtc(createdDate);
        this.createdDateAsLocal = DateConverter.convertZonedToLocal(this.createdDateAsUtc);
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
        this.lastUpdateAsUtc = DateConverter.convertTimestampToUtc(lastUpdate);
        this.lastUpdateAsLocal = DateConverter.convertZonedToLocal(this.lastUpdateAsUtc);
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public ZonedDateTime getCreatedDateAsUtc() {
        return createdDateAsUtc;
    }

    public void setCreatedDateAsUtc(ZonedDateTime createdDateAsUtc) {
        this.createdDateAsUtc = createdDateAsUtc;
        this.createdDateAsLocal = DateConverter.convertZonedToLocal(createdDateAsUtc);
        this.createdDate = DateConverter.convertUtcToTimestamp(createdDateAsUtc);
    }

    public ZonedDateTime getLastUpdateAsUtc() {
        return lastUpdateAsUtc;
    }

    public void setLastUpdateAsUtc(ZonedDateTime lastUpdateAsUtc) {
        this.lastUpdateAsUtc = lastUpdateAsUtc;
        this.lastUpdateAsLocal = DateConverter.convertZonedToLocal(lastUpdateAsUtc);
        this.lastUpdate = DateConverter.convertUtcToTimestamp(lastUpdateAsUtc);
    }

    public LocalDateTime getCreatedDateAsLocal() {
        return createdDateAsLocal;
    }

    public void setCreatedDateAsLocal(LocalDateTime createdDateAsLocal) {
        this.createdDateAsLocal = createdDateAsLocal;
        this.createdDateAsUtc = DateConverter.convertSystemLocalDateTimeToUtc(createdDateAsLocal);
        this.createdDate = DateConverter.convertUtcToTimestamp(this.createdDateAsUtc);
    }

    public LocalDateTime getLastUpdateAsLocal() {
        return lastUpdateAsLocal;
    }

    public void setLastUpdateAsLocal(LocalDateTime lastUpdateAsLocal) {
        this.lastUpdateAsLocal = lastUpdateAsLocal;
        this.lastUpdateAsUtc = DateConverter.convertSystemLocalDateTimeToUtc(lastUpdateAsLocal);
        this.lastUpdate = DateConverter.convertUtcToTimestamp(this.lastUpdateAsUtc);
    }
}
